"""
read_data
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from airflow.providers.google.cloud.operators.dataproc import DataprocSubmitSparkJobOperator
import pendulum


default_args={
    "owner": "Arunkumar MG,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-06-28", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Arunkumar MG": "mailto:arunkumarmg9127@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clxyrrb9i0jjd01nwb8qp1e2t/cloud-ide/clxyv9ps30jzv01k22cjvcay8/clxyva91b0k2a01nwgs8rguv2",
    },
)
def read_data():
    saprk_job = DataprocSubmitSparkJobOperator(
        region="asia-south1",
        job_name="success_rate",
        cluster_name="asia-south1-a",
        project_id="double-kite-427812-r9",
        main_class="success_rate.py",
        arguments=["project_id", "path"],
        task_id="saprk_job",
    )

dag_obj = read_data()
